config/routes.rb
Workterest::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about_path
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end
 
  def show
  end

  def new
    @pin = Pin.new
  end

  def edit
  end

  def create
    @pin = Pin.new(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
    else
      render action: 'new' 
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url 
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<hr >
	  <p>&copy; Workterest 2014</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

<div class="container"> 
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "WORKTEREST", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "HOME", root_path %></li>
      <li><%= link_to "ABOUT", about_path %></li>
      <li><%= link_to "CONTACT", "#contact" %></li>
      <% if user_signed_in? %>
      <li><%= link_to "ACCOUNT SETTINGS", edit_user_registration_path %></li>
      <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "SIGN IN", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workterest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

	<div class="container">
		<%= render 'layouts/header' %>
	</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
	
	
		<%= yield %>

</body>

</html>


<div class="container">
<%= render 'layouts/footer' %>
</div>

app/views/pages/about.html.erb
<div class="container">
	<h1>About</h1>
<p>We are building a Workterest app</p>
</div>

<hr>

app/views/pages/home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->

<div class="specialjumb">
  <div class="container-fluid">
    <h1>Welcome to Workterest!</h1>
    <% if user_signed_in? %>
    <h4>Share Something Phenomenal</h4>
    <% else %>
      <p>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      </p>
    <% end %>
  </div>
</div>

<div class="about">
  <div class="container"> <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
       <h3><span class="glyphicon glyphicon-pushpin"></span> Curate</h3>
        <p>Curate knowledge. There is so much out there. Help guide your teams to knowledge-share.</p>
    </div>
    <div class="col-md-4">
    <h3><span class="glyphicon glyphicon-share-alt"></span> Share</h3>
      <p>Share what you know. Share useful knowledge with your team. Send to them to learn. Help brainstorm.</p>
    </div>
    <div class="col-md-4">
      <h3><span class="glyphicon glyphicon-wrench"></span> Build</h3>
      <p>Build skills and a training path for your team. Grow your team's skills.</p>
    </div>
  </div>
  </div> 
</div>

<a name="contact"></a>
<div class="contact">
  <div class="container"> <!-- Example row of columns -->
    <h2>Contact Us</h2>
    <%= link_to "hello@workterest.com", "mailto:hello@workterest.com?Subject=Hey Workterest" %>
</div>
</div>

<!-- /container -->

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel-body">
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>


  <div class="form group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<br >
</div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">

<h1>Editing pin</h1>

<%= render 'form' %>

<div class="panel-footer">
	<%= link_to 'Show', @pin %> |
	<%= link_to 'Back', pins_path %>
</div>

</div>

app/views/pins/index.html.erb
<div class="container">
  <h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

</div>

app/views/pins/new.html.erb
<div class="container">

	<h1>New Pin</h1>
	
	<%= render 'form' %>

	<div class="panel-footer">
		<%= link_to 'Back', pins_path %>
	</div>

</div>

app/views/pins/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<div class="panel-footer">
	<%= link_to 'Edit', edit_pin_path(@pin) %> |
	<%= link_to 'Back', pins_path %>
</div>

</div>